### ISSUE TITLE
Update library functions to match design guide

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_LSM9DS1#4]
https://circuitpython.readthedocs.io/en/latest/docs/design_guide.html#sensor-properties-and-units

Accelerometer, magnetometer, and gyroscope need to be updated.

**Comment by caternuson** [comment]
Need to:
- [x] Release with major version bump
- [ ] Make sure related guides and example code is updated.

**Comment by caternuson** [comment]
Fixed by #9
